blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . sitemaps import BlogSitemap
from . feeds import RssSiteNewsFeed, AtomSiteNewsFeed

from . import views

app_name = 'blog'


sitemaps = {
    'post': BlogSitemap,
    }

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('post/<slug:category>/<slug:slug>/', views.PostView.as_view(), name='post'),
    path('category/<slug:slug>/', views.CategoryView.as_view(), name='category'),
    path('sitemap/', views.SitemapView.as_view(), name='sitemap'),
    path('page/<slug:slug>/', views.PageView.as_view(), name='page'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('search/', views.SearchView.as_view(), name='search'),
]

#ajax
urlpatterns += [
    path('add-comment/', views.AddCommentPostView.as_view(), name='add_comment'),
    path('refresh-captcha/', views.RefreshCaptchaView.as_view(), name='refresh_captcha'),
    path('online-user-ajax/', views.OnlineUserView.as_view(), name='online_user_ajax'),
]

#redirect
urlpatterns += [
    path('redirect-external/<slug:slug>/', views.RedirectExternalView.as_view(), name='redirect_external'),
]


#xml страницы
urlpatterns += [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('sitenews/rss/', RssSiteNewsFeed(), name='rss'),
    path('sitenews/atom/', AtomSiteNewsFeed(), name='atom'),
]

rukinekryki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('script/', include('script.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('filebrowser_filer/', include('ckeditor_filebrowser_filer.urls')),
]

#капча
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/footer.html
<footer id="app-footer">
    <div class="line-black"></div>
    <div class="container-fluid">
       <div class="row black-fon pt-4 pb-2">
          <div class="col-md-6 left-box">
              <p><a href="/">Руки не крюки - сайт для столяров и плотников</a></p>
              <p>&copy; 2019 - {% now "Y" %} Егор Астапов | сайт мониторится <a href="/redirect-external/ping-admin-index" target="_blank">ping-admin</a></p>
          </div>
           <div class="col-md-6 right-box">
               <p>количество статей: <span id="online-post">{{ post }}</span> | кол-во комментариев: <span id="online-comment">{{ comment }}</span> | онлайн: <span id="online-user">{{ online }}</span></p>
          </div>
       </div>
     </div>
</footer>

templates/base/header.html
{% load staticfiles %}
<header>
  <div class="banner">
       <img src="{% static 'image/banner.png' %}" class="img-fluid d-none d-md-block" alt="Руки не крюки">
  </div>
  <div class="container-fluid">
       <div class="row">
          <div class="col-md-12 menu-top">
            <div class="col-lg-4 col-md-3 d-none d-lg-block">
                <nav class="navbar navbar-expand-lg">
                    <div class="collapse navbar-collapse" id="navbar1">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:sitemap' %}"><i class="fa fa-sitemap" title="Карта сайта"></i></a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'blog:rss' %}" title="RSS-канал"><i class="fa fa-rss"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:atom' %}" title="ATOM-канал">ATOM</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:contact' %}"><i class="far fa-envelope" title="Контакты"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:page' 'about-me' %}"><i class="far fa-user" title="Обо мне"></i></a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
          </div>
          <div class="col-sm-12 d-lg-none menu-top-small">
                <nav class="navbar">
                    <div class="navbar-expand" id="navbar2">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:sitemap' %}"><i class="fa fa-sitemap" title="Карта сайта"></i></a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'blog:rss' %}" title="RSS-канал"><i class="fa fa-rss"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:atom' %}" title="ATOM-канал">ATOM</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:contact' %}"><i class="far fa-envelope" title="Контакты"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:page' 'about-me' %}"><i class="far fa-user" title="Обо мне"></i></a>
                            </li>

                        </ul>
                    </div>
                </nav>
          </div>

       </div>
  </div>
</header>