blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . sitemaps import BlogSitemap
from . feeds import RssSiteNewsFeed, AtomSiteNewsFeed

from . import views

app_name = 'blog'


sitemaps = {
    'post': BlogSitemap,
    }

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('post/<slug:category>/<slug:slug>/', views.PostView.as_view(), name='post'),
    path('category/<slug:slug>/', views.CategoryView.as_view(), name='category'),
    path('sitemap/', views.SitemapView.as_view(), name='sitemap'),
    path('page/<slug:slug>/', views.PageView.as_view(), name='page'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('search/', views.SearchView.as_view(), name='search'),
]

#ajax
urlpatterns += [
    path('add-comment/', views.AddCommentPostView.as_view(), name='add_comment'),
    path('refresh-captcha/', views.RefreshCaptchaView.as_view(), name='refresh_captcha'),
    path('online-user-ajax/', views.OnlineUserView.as_view(), name='online_user_ajax'),
]

#redirect
urlpatterns += [
    path('redirect-external/<slug:slug>/', views.RedirectExternalView.as_view(), name='redirect_external'),
]


#xml страницы
urlpatterns += [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('sitenews/rss/', RssSiteNewsFeed(), name='rss'),
    path('sitenews/atom/', AtomSiteNewsFeed(), name='atom'),
]

rukinekryki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('script/', include('script.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('filebrowser_filer/', include('ckeditor_filebrowser_filer.urls')),
]

#капча
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

script/urls.py
from django.urls import path

from . import views

app_name = 'script'


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("paint-consumption/", views.PaintConsumptionView.as_view(), name="paint_consumption"),
    path("hole-marking/", views.HoleMarkingView.as_view(), name="hole_marking"),
    path("mounting-sheet/", views.MountingSheetView.as_view(), name="mounting_sheet"),
    path("law-ohm/", views.LawOhmView.as_view(), name="law_ohm"),
]

blog/forms.py
# -*- coding: utf-8 -*-
from captcha.fields import CaptchaField

from django import forms
from .models import Category, CommentPost


class SearchForm(forms.Form):

    search = forms.CharField(
        required=True,
        max_length=60,
        # label="Поиск",
        label='',
        widget=forms.TextInput(attrs={'v-model': 'search'})
    )

    type_choices = (
        ('full', 'текст'),
        ('words', 'слова (через пробел)'),
    )

    select_type = forms.ChoiceField(
        required=False,
        # label='Режим поиска',
        label='',
        # widget=forms.Select(attrs={"v-model": "select_type"}),
        widget=forms.Select(),
        choices=type_choices,
    )


    select_category = forms.ModelChoiceField(
        required=False,
        label='',
        queryset=Category.objects.all(),
    )


class CommentPostForm(forms.ModelForm):
    captcha = CaptchaField(label='капча:')

    class Meta:
        model = CommentPost

        fields = ('name_user', 'email_user', 'text', 'post')
        labels = {
            'name_user': "имя пользователя *",
            'text': "сообщение *",
        }
        widgets = {
            'name_user': forms.TextInput(attrs={'class': 'form-control', 'v-model.trim.lazy': 'name_user'}),
            'email_user': forms.EmailInput(attrs={'class': 'form-control', 'v-model.trim.lazy': 'email_user'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 7, 'v-model.trim.lazy': 'text'}),
            'post': forms.HiddenInput(attrs={'ref': 'post_id'}),
        }

templates/base.html
{% load staticfiles %}
{% load mptt_tags %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block description %}{% endblock%}">
    <meta name="keywords" content="{% block keywords %}{% endblock%}" />

    <title>{% block title %}{% endblock%}</title>
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- font-awesome  -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static '/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static '/favicon.ico' %}" type="image/x-icon">

    <!-- Bootstrap -->
    {# <script src="{% static 'js/bootstrap.min.js' %}"></script> #}
    <!--my scripts-->
    {# <script src="{% static 'js/scripts.js' %}"></script> #}
    <!--vue scripts-->
    <script src="{% static 'js/vue.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios@0.12.0/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.13.1/lodash.min.js"></script>
</head>
<body>

{% include 'base/header.html' %}

<main role="main">
    <div class="container-fluid">
       <div class="row">
           {# левый блок #}
          <div class="col-lg-2 col-md-2">
              <div class="side pt-2">

                <p>Категории</p>
                <ul class="root">
                    {% recursetree category_side %}
                    <li>
                        <a href="{% url 'blog:category' node.slug %}">{{ node.name|capfirst  }}</a>
                        {% if not node.is_child_node %}
                            <ul class="children">
                                {{ children }}
                            </ul>
                        {% endif %}
                    </li>
                    {% endrecursetree %}
                </ul>

                <p>Последние статьи</p>
                <ul>
                    {% for post in post_side %}
                        <li class="mb-2"><a href="{% url 'blog:post' post.category.slug post.slug %}">{{ post.name|capfirst  }}</a></li>
                    {% endfor %}
                </ul>

                <p>Скрипты</p>
                <ul>
                    <li><a href="{% url 'script:paint_consumption' %}">Расход краски</a></li>
                    <li><a href="{% url 'script:hole_marking' %}">Разметка отверстий</a></li>
                    <li><a href="{% url 'script:mounting_sheet' %}">Расчёт монтажа</a></li>
                    <li><a href="{% url 'script:law_ohm' %}">Закон Ома</a></li>
                </ul>

                {% comment %}
                <p>Голосование</p>
                <ul>
                    <li><a href="#">000</a></li>
                    <li><a href="#">000</a></li>
                </ul>
                {% endcomment %}
                <noindex>
                    <div class="yandex-counter">
                        <!-- Yandex.Metrika informer -->
                        <a href="https://metrika.yandex.ru/stat/?id=53428576&amp;from=informer"
                        target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/53428576/3_0_FFF3C5FF_FFD3A5FF_0_pageviews"
                        style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" class="ym-advanced-informer" data-cid="53428576" data-lang="ru" /></a>
                        <!-- /Yandex.Metrika informer -->

                        <!-- Yandex.Metrika counter -->
                        <script type="text/javascript" >
                           (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
                           m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
                           (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

                           ym(53428576, "init", {
                                clickmap:true,
                                trackLinks:true,
                                accurateTrackBounce:true
                           });
                        </script>
                        <noscript><div><img src="https://mc.yandex.ru/watch/53428576" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
                        <!-- /Yandex.Metrika counter -->
                    </div>
                </noindex>
              </div>
          </div>
           {# средний блок - контент #}
          <div class="col-lg-8 col-md-10">
              {% block content %}{% endblock%}
          </div>
           {# правый блок #}
          <div class="col-lg-2 d-none d-lg-block">
            <div class="side pt-2">
                {% if sites_friends_side %}
                <p>Сайты друзей</p>
                <ul>
                    {% for sites in sites_friends_side %}
                        <li class="mb-2"><a href="{{ sites.url }}" target="_blank" title="{{ sites.text }}">{{ sites.name }}</a></li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% if form_search %}
                <p>Поиск</p>
                <div class="search" id="app-search">
                    <form action="{% url 'blog:search' %}" method="post" class="search">
                        {% csrf_token %}
                        {{ form_search.as_p }}
                        <input id="submit_search" type="submit" value="поиск">
                    </form>
                {% endif %}
                </div>
                <script>
                var app_search = new Vue({
                  el: '#app-search',
                  data: {
                    search: document.querySelector('#id_search').value,
                  },
                  watch: {
                    search: function (val) {
                        if(val.length > 0){
                            this.view_input('inline');
                        }else{
                            this.view_input('none');
                        }
                    },
                  },
                  mounted: function(){
                     //есть ли данные в форме
                     if(this.search.length > 0){
                        this.view_input('inline');
                     }
                  },
                  methods: {
                    view_input: function(val){
                        //показываем/скрываем все поля
                        document.querySelector('#id_select_type').style.display = val
                        document.querySelector('#id_select_category').style.display = val
                        document.querySelector('#submit_search').style.display = val
                    }
                  },
                })
                </script>
                {% comment %}
                <p>Реклама</p>
                <div class="advertising">
                    <img src="{% static 'image/reklama160x600.png' %}">
                </div>
                {% endcomment %}
              </div>
          </div>
       </div>
    </div>
</main>

{# нижний блок - футер #}
{% include 'base/footer.html' with post=info.post comment=info.comment online=online only %}

<script src="{% static 'js/online_user.js' %}"></script>
{% block script_vue %}{% endblock %}

</body>
</html>